package config

import "sourcegraph.com/sourcegraph/srclib/unit"

var overrides = map[string]*Repository{
	"github.com/meteor/meteor": {
		URI: "github.com/meteor/meteor",
		Tree: Tree{
			SourceUnits: []*unit.SourceUnit{
				{
					Name: "meteor",
					Type: "CommonJSPackage",
					Dir:  ".",
					Config: map[string]interface{}{
						"jsg": map[string]interface{}{
							"plugins": map[string]interface{}{
								"node": map[string]string{"coreModulesDir": "lib/"},
								"$(JSG_DIR)/node_modules/tern-node-api-doc/node-api-doc": map[string]string{
									"apiDocDir":      "doc/api/",
									"apiSrcDir":      "lib/",
									"generateJSPath": "tools/doc/generate.js",
								},
							},
						},
					},
					Files: []string{
						"./packages/accounts-password/email_tests.js",
						"./packages/accounts-password/password_server.js",
						"./packages/accounts-password/password_client.js",
						"./packages/accounts-password/package.js",
						"./packages/accounts-password/password_tests_setup.js",
						"./packages/accounts-password/email_tests_setup.js",
						"./packages/accounts-password/email_templates.js",
						"./packages/accounts-password/password_tests.js",
						"./packages/spiderable/spiderable_server.js",
						"./packages/spiderable/spiderable.js",
						"./packages/spiderable/package.js",
						"./packages/spiderable/phantom_script.js",
						"./packages/spiderable/spiderable_client.js",
						"./packages/spiderable/spiderable_tests.js",
						"./packages/geojson-utils/package.js",
						"./packages/geojson-utils/pre.js",
						"./packages/geojson-utils/geojson-utils.js",
						"./packages/geojson-utils/geojson-utils.tests.js",
						"./packages/geojson-utils/post.js",
						"./packages/json/json_native.js",
						"./packages/json/package.js",
						"./packages/json/json2.js",
						"./packages/follower-livedata/package.js",
						"./packages/follower-livedata/follower.js",
						"./packages/accounts-twitter/package.js",
						"./packages/accounts-twitter/twitter.js",
						"./packages/google/google_configure.js",
						"./packages/google/package.js",
						"./packages/google/google_client.js",
						"./packages/google/google_server.js",
						"./packages/reload/reload.js",
						"./packages/reload/package.js",
						"./packages/reload/reload_tests.js",
						"./packages/reload/deprecated.js",
						"./packages/random/random.js",
						"./packages/random/package.js",
						"./packages/random/random_tests.js",
						"./packages/random/deprecated.js",
						"./packages/minimongo/projection.js",
						"./packages/minimongo/selector_projection.js",
						"./packages/minimongo/sorter_projection.js",
						"./packages/minimongo/minimongo_tests.js",
						"./packages/minimongo/modify.js",
						"./packages/minimongo/id_map.js",
						"./packages/minimongo/sort.js",
						"./packages/minimongo/package.js",
						"./packages/minimongo/observe.js",
						"./packages/minimongo/selector.js",
						"./packages/minimongo/selector_modifier.js",
						"./packages/minimongo/wrap_transform.js",
						"./packages/minimongo/wrap_transform_tests.js",
						"./packages/minimongo/diff.js",
						"./packages/minimongo/minimongo.js",
						"./packages/minimongo/minimongo_server_tests.js",
						"./packages/minimongo/objectid.js",
						"./packages/minimongo/helpers.js",
						"./packages/meetup/meetup_configure.js",
						"./packages/meetup/package.js",
						"./packages/meetup/meetup_server.js",
						"./packages/meetup/meetup_client.js",
						"./packages/package-version-parser/package.js",
						"./packages/package-version-parser/package-version-parser-tests.js",
						"./packages/package-version-parser/package-version-parser.js",
						"./packages/meteor-platform/package.js",
						"./packages/logging/logging.js",
						"./packages/logging/logging_cordova.js",
						"./packages/logging/package.js",
						"./packages/logging/logging_test.js",
						"./packages/js-analyze-tests/package.js",
						"./packages/js-analyze-tests/js_analyze_tests.js",
						"./packages/accounts-ui-unstyled/login_buttons_session.js",
						"./packages/accounts-ui-unstyled/package.js",
						"./packages/accounts-ui-unstyled/login_buttons_single.js",
						"./packages/accounts-ui-unstyled/login_buttons_dialogs.js",
						"./packages/accounts-ui-unstyled/login_buttons.js",
						"./packages/accounts-ui-unstyled/login_buttons_dropdown.js",
						"./packages/accounts-ui-unstyled/accounts_ui_tests.js",
						"./packages/accounts-ui-unstyled/accounts_ui.js",
						"./packages/mongo/remote_collection_driver.js",
						"./packages/mongo/collection.js",
						"./packages/mongo/oplog_tests.js",
						"./packages/mongo/doc_fetcher_tests.js",
						"./packages/mongo/doc_fetcher.js",
						"./packages/mongo/allow_tests.js",
						"./packages/mongo/observe_changes_tests.js",
						"./packages/mongo/observe_multiplex.js",
						"./packages/mongo/package.js",
						"./packages/mongo/oplog_tailing.js",
						"./packages/mongo/mongo_driver.js",
						"./packages/mongo/polling_observe_driver.js",
						"./packages/mongo/mongo_livedata_tests.js",
						"./packages/mongo/collection_tests.js",
						"./packages/mongo/oplog_observe_driver.js",
						"./packages/mongo/local_collection_driver.js",
						"./packages/callback-hook/package.js",
						"./packages/callback-hook/hook.js",
						"./packages/fastclick/fastclick.js",
						"./packages/fastclick/package.js",
						"./packages/fastclick/pre.js",
						"./packages/fastclick/post.js",
						"./packages/livedata/package.js",
						"./packages/handlebars/package.js",
						"./packages/test-in-console/package.js",
						"./packages/test-in-console/driver.js",
						"./packages/test-in-console/reporter.js",
						"./packages/test-in-console/runner.js",
						"./packages/htmljs/package.js",
						"./packages/htmljs/htmljs_test.js",
						"./packages/htmljs/preamble.js",
						"./packages/htmljs/html.js",
						"./packages/htmljs/visitors.js",
						"./packages/check/match.js",
						"./packages/check/match_test.js",
						"./packages/check/package.js",
						"./packages/autoupdate/autoupdate_cordova.js",
						"./packages/autoupdate/package.js",
						"./packages/autoupdate/autoupdate_client.js",
						"./packages/autoupdate/autoupdate_server.js",
						"./packages/twitter/package.js",
						"./packages/twitter/twitter_server.js",
						"./packages/twitter/twitter_configure.js",
						"./packages/twitter/twitter_client.js",
						"./packages/less/package.js",
						"./packages/less/plugin/compile-less.js",
						"./packages/less/less_tests.js",
						"./packages/ctl-helper/package.js",
						"./packages/ctl-helper/ctl-helper.js",
						"./packages/accounts-github/package.js",
						"./packages/accounts-github/github.js",
						"./packages/launch-screen/package.js",
						"./packages/launch-screen/mobile-launch-screen.js",
						"./packages/launch-screen/default-behavior.js",
						"./packages/browser-policy-framing/package.js",
						"./packages/browser-policy-framing/browser-policy-framing.js",
						"./packages/standard-app-packages/package.js",
						"./packages/ordered-dict/ordered_dict.js",
						"./packages/ordered-dict/package.js",
						"./packages/browser-policy/package.js",
						"./packages/browser-policy/browser-policy-test.js",
						"./packages/mongo-livedata/package.js",
						"./packages/oauth-encryption/package.js",
						"./packages/oauth-encryption/encrypt.js",
						"./packages/oauth-encryption/encrypt_tests.js",
						"./packages/accounts-oauth/oauth_server.js",
						"./packages/accounts-oauth/package.js",
						"./packages/accounts-oauth/oauth_common.js",
						"./packages/accounts-oauth/oauth_tests.js",
						"./packages/accounts-oauth/oauth_client.js",
						"./packages/non-core/jquery-layout/package.js",
						"./packages/non-core/jquery-layout/jquery.layout.js",
						"./packages/non-core/jquery-history/history.js",
						"./packages/non-core/jquery-history/package.js",
						"./packages/non-core/jquery-history/history.adapter.jquery.js",
						"./packages/non-core/jquery-history/history.html4.js",
						"./packages/non-core/npm-node-aes-gcm/package.js",
						"./packages/non-core/npm-node-aes-gcm/wrapper.js",
						"./packages/non-core/npm-bcrypt/package.js",
						"./packages/non-core/npm-bcrypt/wrapper.js",
						"./packages/weibo/package.js",
						"./packages/weibo/weibo_client.js",
						"./packages/weibo/weibo_server.js",
						"./packages/weibo/weibo_configure.js",
						"./packages/jquery-waypoints/package.js",
						"./packages/preserve-inputs/package.js",
						"./packages/preserve-inputs/deprecated.js",
						"./packages/minifiers/minifiers.js",
						"./packages/minifiers/urlrewriting-tests.js",
						"./packages/minifiers/minifiers-tests.js",
						"./packages/minifiers/minification.js",
						"./packages/minifiers/package.js",
						"./packages/minifiers/beautify-tests.js",
						"./packages/ejson/custom_models_for_tests.js",
						"./packages/ejson/ejson_test.js",
						"./packages/ejson/package.js",
						"./packages/ejson/ejson.js",
						"./packages/ejson/stringify.js",
						"./packages/email/email_tests.js",
						"./packages/email/package.js",
						"./packages/email/email.js",
						"./packages/spacebars-compiler/package.js",
						"./packages/spacebars-compiler/spacebars_tests.js",
						"./packages/spacebars-compiler/compile_tests.js",
						"./packages/spacebars-compiler/codegen.js",
						"./packages/spacebars-compiler/templatetag.js",
						"./packages/spacebars-compiler/compiler.js",
						"./packages/spacebars-compiler/optimizer.js",
						"./packages/force-ssl/package.js",
						"./packages/force-ssl/force_ssl_common.js",
						"./packages/force-ssl/force_ssl_server.js",
						"./packages/blaze-tools/token_tests.js",
						"./packages/blaze-tools/package.js",
						"./packages/blaze-tools/preamble.js",
						"./packages/blaze-tools/tojs.js",
						"./packages/blaze-tools/tokens.js",
						"./packages/meteor/bare_test_setup.js",
						"./packages/meteor/cordova_environment_test.js",
						"./packages/meteor/dynamics_nodejs.js",
						"./packages/meteor/helpers_test.js",
						"./packages/meteor/client_environment_test.js",
						"./packages/meteor/dynamics_test.js",
						"./packages/meteor/url_tests.js",
						"./packages/meteor/timers_tests.js",
						"./packages/meteor/cordova_environment.js",
						"./packages/meteor/client_environment.js",
						"./packages/meteor/dynamics_browser.js",
						"./packages/meteor/wrapasync_test.js",
						"./packages/meteor/fiber_helpers.js",
						"./packages/meteor/package.js",
						"./packages/meteor/url_server.js",
						"./packages/meteor/setimmediate.js",
						"./packages/meteor/debug.js",
						"./packages/meteor/server_environment_test.js",
						"./packages/meteor/plugin/basic-file-types.js",
						"./packages/meteor/startup_client.js",
						"./packages/meteor/errors.js",
						"./packages/meteor/fiber_helpers_test.js",
						"./packages/meteor/server_environment.js",
						"./packages/meteor/bare_tests.js",
						"./packages/meteor/browser_environment_test.js",
						"./packages/meteor/debug_test.js",
						"./packages/meteor/url_common.js",
						"./packages/meteor/timers.js",
						"./packages/meteor/fiber_stubs_client.js",
						"./packages/meteor/helpers.js",
						"./packages/meteor/startup_server.js",
						"./packages/dev-bundle-fetcher/dev-bundle.js",
						"./packages/dev-bundle-fetcher/package.js",
						"./packages/accounts-weibo/weibo.js",
						"./packages/accounts-weibo/package.js",
						"./packages/id-map/package.js",
						"./packages/id-map/id-map.js",
						"./packages/base64/base64.js",
						"./packages/base64/base64_test.js",
						"./packages/base64/package.js",
						"./packages/application-configuration/package.js",
						"./packages/application-configuration/config.js",
						"./packages/facebook/facebook_client.js",
						"./packages/facebook/package.js",
						"./packages/facebook/facebook_server.js",
						"./packages/facebook/facebook_configure.js",
						"./packages/xmlbuilder/package.js",
						"./packages/xmlbuilder/xmlbuilder.js",
						"./packages/reactive-var/package.js",
						"./packages/reactive-var/reactive-var.js",
						"./packages/accounts-base/accounts_tests.js",
						"./packages/accounts-base/accounts_url_tests.js",
						"./packages/accounts-base/package.js",
						"./packages/accounts-base/url_client.js",
						"./packages/accounts-base/url_server.js",
						"./packages/accounts-base/accounts_server.js",
						"./packages/accounts-base/localstorage_token.js",
						"./packages/accounts-base/accounts_common.js",
						"./packages/accounts-base/accounts_client.js",
						"./packages/webapp/webapp_tests.js",
						"./packages/webapp/package.js",
						"./packages/webapp/webapp_client.js",
						"./packages/webapp/webapp_server.js",
						"./packages/tracker/tracker_tests.js",
						"./packages/tracker/package.js",
						"./packages/tracker/tracker.js",
						"./packages/tracker/deprecated.js",
						"./packages/coffeescript-test-helper/package.js",
						"./packages/code-prettify/lang-clj.js",
						"./packages/code-prettify/prettify.js",
						"./packages/code-prettify/lang-yaml.js",
						"./packages/code-prettify/lang-scala.js",
						"./packages/code-prettify/lang-vhdl.js",
						"./packages/code-prettify/lang-apollo.js",
						"./packages/code-prettify/lang-css.js",
						"./packages/code-prettify/lang-wiki.js",
						"./packages/code-prettify/lang-go.js",
						"./packages/code-prettify/lang-n.js",
						"./packages/code-prettify/package.js",
						"./packages/code-prettify/lang-lisp.js",
						"./packages/code-prettify/lang-hs.js",
						"./packages/code-prettify/lang-sql.js",
						"./packages/code-prettify/lang-proto.js",
						"./packages/code-prettify/lang-ml.js",
						"./packages/code-prettify/lang-vb.js",
						"./packages/code-prettify/lang-lua.js",
						"./packages/code-prettify/lang-tex.js",
						"./packages/code-prettify/lang-xq.js",
						"./packages/accounts-meetup/package.js",
						"./packages/accounts-meetup/meetup.js",
						"./packages/markdown/package.js",
						"./packages/markdown/template-integration.js",
						"./packages/markdown/showdown.js",
						"./packages/insecure/package.js",
						"./packages/retry/package.js",
						"./packages/retry/retry.js",
						"./packages/test-in-browser/autoupdate.js",
						"./packages/test-in-browser/diff_match_patch_uncompressed.js",
						"./packages/test-in-browser/package.js",
						"./packages/test-in-browser/driver.js",
						"./packages/jsparse/parser.js",
						"./packages/jsparse/package.js",
						"./packages/jsparse/stringify.js",
						"./packages/jsparse/parserlib.js",
						"./packages/jsparse/lexer.js",
						"./packages/jsparse/parser_tests.js",
						"./packages/session/session.js",
						"./packages/session/package.js",
						"./packages/session/session_tests.js",
						"./packages/underscore/package.js",
						"./packages/underscore/pre.js",
						"./packages/underscore/underscore.js",
						"./packages/underscore/post.js",
						"./packages/browser-policy-common/package.js",
						"./packages/browser-policy-common/browser-policy-common.js",
						"./packages/meteor-tool/package.js",
						"./packages/oauth1/oauth1_tests.js",
						"./packages/oauth1/package.js",
						"./packages/oauth1/oauth1_binding.js",
						"./packages/oauth1/oauth1_server.js",
						"./packages/oauth1/oauth1_pending_request_tokens.js",
						"./packages/disable-oplog/package.js",
						"./packages/spacebars/dynamic.js",
						"./packages/spacebars/package.js",
						"./packages/spacebars/dynamic_tests.js",
						"./packages/spacebars/spacebars-runtime.js",
						"./packages/underscore-tests/package.js",
						"./packages/underscore-tests/each_test.js",
						"./packages/package-stats-opt-out/package.js",
						"./packages/audit-argument-checks/package.js",
						"./packages/constraint-solver/resolver-state.js",
						"./packages/constraint-solver/test-data.js",
						"./packages/constraint-solver/benchmark-tests.js",
						"./packages/constraint-solver/constraints-list.js",
						"./packages/constraint-solver/package.js",
						"./packages/constraint-solver/constraint-solver-tests.js",
						"./packages/constraint-solver/priority-queue.js",
						"./packages/constraint-solver/constraint-solver.js",
						"./packages/constraint-solver/resolver.js",
						"./packages/constraint-solver/resolver-tests.js",
						"./packages/test-server-tests-in-console-once/package.js",
						"./packages/test-server-tests-in-console-once/server.js",
						"./packages/js-analyze/js_analyze.js",
						"./packages/js-analyze/package.js",
						"./packages/oauth2/package.js",
						"./packages/oauth2/oauth2_tests.js",
						"./packages/oauth2/oauth2_server.js",
						"./packages/templating/scanner_tests.js",
						"./packages/templating/package.js",
						"./packages/templating/plugin/html_scanner.js",
						"./packages/templating/plugin/compile-templates.js",
						"./packages/templating/templating.js",
						"./packages/deps/package.js",
						"./packages/http/test_responder.js",
						"./packages/http/httpcall_server.js",
						"./packages/http/package.js",
						"./packages/http/httpcall_client.js",
						"./packages/http/httpcall_common.js",
						"./packages/http/httpcall_tests.js",
						"./packages/http/deprecated.js",
						"./packages/star-translate/translator.js",
						"./packages/star-translate/package.js",
						"./packages/ctl/ctl.js",
						"./packages/ctl/package.js",
						"./packages/webapp-hashing/webapp-hashing.js",
						"./packages/webapp-hashing/package.js",
						"./packages/blaze/dombackend.js",
						"./packages/blaze/materializer.js",
						"./packages/blaze/render_tests.js",
						"./packages/blaze/view.js",
						"./packages/blaze/attrs.js",
						"./packages/blaze/exceptions.js",
						"./packages/blaze/events.js",
						"./packages/blaze/microscore.js",
						"./packages/blaze/domrange.js",
						"./packages/blaze/package.js",
						"./packages/blaze/preamble.js",
						"./packages/blaze/view_tests.js",
						"./packages/blaze/builtins.js",
						"./packages/blaze/template.js",
						"./packages/blaze/lookup.js",
						"./packages/blaze/backcompat.js",
						"./packages/oauth/oauth_browser.js",
						"./packages/oauth/oauth_cordova.js",
						"./packages/oauth/oauth_server.js",
						"./packages/oauth/package.js",
						"./packages/oauth/oauth_common.js",
						"./packages/oauth/oauth_tests.js",
						"./packages/oauth/oauth_client.js",
						"./packages/oauth/pending_credentials.js",
						"./packages/oauth/deprecated.js",
						"./packages/srp/srp_tests.js",
						"./packages/srp/package.js",
						"./packages/srp/biginteger.js",
						"./packages/srp/srp.js",
						"./packages/html-tools/scanner.js",
						"./packages/html-tools/tokenize_tests.js",
						"./packages/html-tools/parse_tests.js",
						"./packages/html-tools/charref_tests.js",
						"./packages/html-tools/package.js",
						"./packages/html-tools/utils.js",
						"./packages/html-tools/tokenize.js",
						"./packages/html-tools/templatetag.js",
						"./packages/html-tools/parse.js",
						"./packages/html-tools/charref.js",
						"./packages/mobile-status-bar/mobile-status-bar.js",
						"./packages/mobile-status-bar/package.js",
						"./packages/meyerweb-reset/package.js",
						"./packages/stylus/stylus_tests.js",
						"./packages/stylus/package.js",
						"./packages/stylus/plugin/compile-stylus.js",
						"./packages/reactive-dict/package.js",
						"./packages/reactive-dict/migration.js",
						"./packages/reactive-dict/reactive-dict.js",
						"./packages/accounts-ui/package.js",
						"./packages/test-helpers/current_style.js",
						"./packages/test-helpers/connection.js",
						"./packages/test-helpers/try_all_permutations_test.js",
						"./packages/test-helpers/event_simulation.js",
						"./packages/test-helpers/try_all_permutations.js",
						"./packages/test-helpers/canonicalize_html.js",
						"./packages/test-helpers/domutils.js",
						"./packages/test-helpers/callback_logger.js",
						"./packages/test-helpers/seeded_random.js",
						"./packages/test-helpers/package.js",
						"./packages/test-helpers/render_div.js",
						"./packages/test-helpers/seeded_random_test.js",
						"./packages/test-helpers/async_multi.js",
						"./packages/facts/package.js",
						"./packages/facts/facts.js",
						"./packages/ddp/random_stream.js",
						"./packages/ddp/livedata_test_service.js",
						"./packages/ddp/livedata_server.js",
						"./packages/ddp/livedata_tests.js",
						"./packages/ddp/crossbar.js",
						"./packages/ddp/common.js",
						"./packages/ddp/package.js",
						"./packages/ddp/session_view_tests.js",
						"./packages/ddp/stream_client_common.js",
						"./packages/ddp/client_convenience.js",
						"./packages/ddp/random_stream_tests.js",
						"./packages/ddp/heartbeat.js",
						"./packages/ddp/livedata_common.js",
						"./packages/ddp/sockjs-0.3.4.js",
						"./packages/ddp/stream_client_nodejs.js",
						"./packages/ddp/writefence.js",
						"./packages/ddp/livedata_connection.js",
						"./packages/ddp/stub_stream.js",
						"./packages/ddp/livedata_server_tests.js",
						"./packages/ddp/crossbar_tests.js",
						"./packages/ddp/livedata_connection_tests.js",
						"./packages/ddp/stream_client_sockjs.js",
						"./packages/ddp/stream_server.js",
						"./packages/ddp/stream_tests.js",
						"./packages/ddp/server_convenience.js",
						"./packages/ddp/stream_client_tests.js",
						"./packages/sha/sha256.js",
						"./packages/sha/package.js",
						"./packages/service-configuration/service_configuration_common.js",
						"./packages/service-configuration/package.js",
						"./packages/accounts-facebook/package.js",
						"./packages/accounts-facebook/facebook.js",
						"./packages/coffeescript/coffeescript_test_setup.js",
						"./packages/coffeescript/package.js",
						"./packages/coffeescript/plugin/compile-coffeescript.js",
						"./packages/coffeescript/coffeescript_tests.js",
						"./packages/coffeescript/bare_tests.js",
						"./packages/showdown/package.js",
						"./packages/startup/package.js",
						"./packages/accounts-google/package.js",
						"./packages/accounts-google/google.js",
						"./packages/spacebars-tests/package.js",
						"./packages/spacebars-tests/old_templates_tests.js",
						"./packages/spacebars-tests/old_templates.js",
						"./packages/spacebars-tests/templating_tests.js",
						"./packages/spacebars-tests/template_tests_server.js",
						"./packages/spacebars-tests/template_tests.js",
						"./packages/meteor-developer/meteor_developer_configure.js",
						"./packages/meteor-developer/meteor_developer_common.js",
						"./packages/meteor-developer/package.js",
						"./packages/meteor-developer/meteor_developer_server.js",
						"./packages/meteor-developer/meteor_developer_client.js",
						"./packages/routepolicy/package.js",
						"./packages/routepolicy/routepolicy.js",
						"./packages/routepolicy/routepolicy_tests.js",
						"./packages/browser-policy-content/browser-policy-content.js",
						"./packages/browser-policy-content/package.js",
						"./packages/reload-safetybelt/safetybelt.js",
						"./packages/reload-safetybelt/reload-safety-belt.js",
						"./packages/reload-safetybelt/package.js",
						"./packages/reload-safetybelt/reload-safety-belt-tests.js",
						"./packages/deprecated/d3/package.js",
						"./packages/deprecated/d3/d3.v3.js",
						"./packages/deprecated/bootstrap/package.js",
						"./packages/deprecated/bootstrap/js/bootstrap.js",
						"./packages/deprecated/backbone/package.js",
						"./packages/deprecated/backbone/backbone.js",
						"./packages/deprecated/amplify/package.js",
						"./packages/deprecated/amplify/amplify.js",
						"./packages/jquery/jquery.js",
						"./packages/jquery/package.js",
						"./packages/jquery/post.js",
						"./packages/observe-sequence/observe_sequence_tests.js",
						"./packages/observe-sequence/package.js",
						"./packages/observe-sequence/observe_sequence.js",
						"./packages/github/package.js",
						"./packages/github/github_configure.js",
						"./packages/github/github_client.js",
						"./packages/github/github_server.js",
						"./packages/accounts-meteor-developer/package.js",
						"./packages/accounts-meteor-developer/meteor-developer.js",
						"./packages/boilerplate-generator/package.js",
						"./packages/boilerplate-generator/boilerplate-generator.js",
						"./packages/autopublish/package.js",
						"./packages/appcache/appcache_tests-server.js",
						"./packages/appcache/package.js",
						"./packages/appcache/appcache_tests-client.js",
						"./packages/appcache/appcache-server.js",
						"./packages/appcache/appcache-client.js",
						"./packages/ui/package.js",
						"./packages/tinytest/tinytest_client.js",
						"./packages/tinytest/tinytest.js",
						"./packages/tinytest/tinytest_server.js",
						"./packages/tinytest/package.js",
						"./packages/tinytest/model.js",
						"./packages/url/package.js",
						"./packages/url/url_client.js",
						"./packages/url/url_server.js",
						"./packages/url/url_common.js",
						"./packages/localstorage/package.js",
						"./packages/localstorage/localstorage_tests.js",
						"./packages/localstorage/localstorage.js",
						"./packages/binary-heap/binary-heap-tests.js",
						"./packages/binary-heap/min-max-heap.js",
						"./packages/binary-heap/max-heap.js",
						"./packages/binary-heap/min-heap.js",
						"./packages/binary-heap/package.js",
					},
				},
			},
		},
	},
	"sourcegraph.com/sourcegraph/sourcegraph": {
		URI: "sourcegraph.com/sourcegraph/sourcegraph",
		Tree: Tree{
			SkipDirs: []string{"app/node_modules", "app/bower_components"},
			SkipUnits: []struct{ Name, Type string }{
				{Name: ".", Type: "ruby"},
				{Name: "app", Type: "CommonJSPackage"},
			},
		},
	},
	"code.google.com/p/rsc": {
		URI: "code.google.com/p/rsc",
		Tree: Tree{
			SkipDirs: []string{"cmd/numbers", "cc"},
		},
	},
	"github.com/emicklei/go-restful": {
		URI: "github.com/emicklei/go-restful",
		Tree: Tree{
			SkipDirs: []string{"examples"},
		},
	},
	"code.google.com/p/go": {
		URI: "code.google.com/p/go",
		Tree: Tree{
			Config:            map[string]interface{}{"GOROOT": "."},
			SkipDirs:          []string{"test", "misc", "doc", "lib", "include"},
			PreConfigCommands: []string{"echo devel > VERSION && cd src && ./make.bash"},
		},
	},
	"github.com/joyent/node": {
		URI: "github.com/joyent/node",
		Tree: Tree{
			SkipDirs: []string{"tools", "deps", "test", "src"},
			SourceUnits: []*unit.SourceUnit{
				{
					Name:  "node",
					Type:  "CommonJSPackage",
					Dir:   ".",
					Files: []string{"lib/*.js"},
					Config: map[string]interface{}{
						"jsg": map[string]interface{}{
							"plugins": map[string]interface{}{
								"node": map[string]string{"coreModulesDir": "lib/"},
								"$(JSG_DIR)/node_modules/tern-node-api-doc/node-api-doc": map[string]string{
									"apiDocDir":      "doc/api/",
									"apiSrcDir":      "lib/",
									"generateJSPath": "tools/doc/generate.js",
								},
							},
						},
					},
				},
			},
		},
	},
	"github.com/ruby/ruby": {
		URI: "github.com/ruby/ruby",
		Tree: Tree{
			SkipDirs: []string{"test", "ext"},
			SourceUnits: []*unit.SourceUnit{
				{
					Name:   ".",
					Type:   "ruby",
					Dir:    ".",
					Config: map[string]interface{}{"noCachedStdlibYardoc": false},
					Files: []string{
						"*.c",
						"lib/*.rb",
						"lib/cgi/*.rb",
						"lib/cgi/session/*.rb",
						"lib/drb/*.rb",
						"lib/irb/*.rb",
						"lib/irb/cmd/*.rb",
						"lib/irb/ext/*.rb",
						"lib/irb/lc/*.rb",
						"lib/irb/lc/ja/*.rb",
						"lib/matrix/*.rb",
						"lib/minitest/*.rb",
						"lib/net/*.rb",
						"lib/net/http/*.rb",
						"lib/optparse/*.rb",
						"lib/racc/*.rb",
						"lib/rake/*.rb",
						"lib/rake/contrib/*.rb",
						"lib/rake/ext/*.rb",
						"lib/rake/loaders/*.rb",
						"lib/rbconfig/*.rb",
						"lib/rdoc/*.rb",
						"lib/rdoc/context/*.rb",
						"lib/rdoc/generator/*.rb",
						"lib/rdoc/markdown/*.rb",
						"lib/rdoc/markup/*.rb",
						"lib/rdoc/parser/*.rb",
						"lib/rdoc/rd/*.rb",
						"lib/rdoc/ri/*.rb",
						"lib/rdoc/stats/*.rb",
						"lib/rexml/*.rb",
						"lib/rexml/dtd/*.rb",
						"lib/rexml/formatters/*.rb",
						"lib/rexml/light/*.rb",
						"lib/rexml/parsers/*.rb",
						"lib/rexml/validation/*.rb",
						"lib/rinda/*.rb",
						"lib/rss/*.rb",
						"lib/rss/content/*.rb",
						"lib/rss/dublincore/*.rb",
						"lib/rss/maker/*.rb",
						"lib/rubygems/*.rb",
						"lib/rubygems/commands/*.rb",
						"lib/rubygems/core_ext/*.rb",
						"lib/rubygems/ext/*.rb",
						"lib/rubygems/package/*.rb",
						"lib/rubygems/package/tar_reader/*.rb",
						"lib/rubygems/request_set/*.rb",
						"lib/rubygems/resolver/*.rb",
						"lib/rubygems/security/*.rb",
						"lib/rubygems/source/*.rb",
						"lib/rubygems/util/*.rb",
						"lib/shell/*.rb",
						"lib/test/*.rb",
						"lib/test/unit/*.rb",
						"lib/uri/*.rb",
						"lib/webrick/*.rb",
						"lib/webrick/httpauth/*.rb",
						"lib/webrick/httpservlet/*.rb",
						"lib/xmlrpc/*.rb",
						"lib/yaml/*.rb",
						// TODO(sqs): should probably add ext/
						// TODO(sqs): it's annoying that filematch.Glob doesn't support
						// '**', so we have to list out each dir here (not just lib/**/*.rb)
					},
				},
			},
		},
	},
}
